var CANVAS_WIDTH = CANVAS_WIDTH;
var CANVAS_HEIGHT = CANVAS_HEIGHT;

var UP = 38;
var DOWN = 40;
var RIGHT = 39;
var LEFT = 37;
var SPACE = 32;

var ENEMY_SPEED = 200;
var GROUND_SPEED = 100;
var ENEMY_BOUNCE_AMT = 250;

var SPRITE_ATLAS = 0;
var HEALTH_BG = 1;
var HEALTH_FG = 2;
var HEALTH_TRANSITION = 3;
var SPLASH_SCREEN = 5;
var GAME_OVER_SCREEN = 6;
var GAME_OVER = 7;

var HEALTH_TRANSITION_TIME = 3;

var PLAYER_START_HEALTH = 10;
var PLAYER_INVULNERABLE_TIME = 3000;
var PLAYER_FLASH_LENGTH = 250;
var PLAYER_DEATH_TIME = 2000;
//var PLAYER_DEAD_FRAME_INDEX = 12;
var AIR_FRICTION = 0.98;